name: getStagingProfile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        submodules: true
        lfs: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'liberica'
    - name: Build with Gradle
      run: ./gradlew getStagingProfile
